### PR TITLE
improved documentation for script usage

### PR DESCRIPTION
**Pull request by ptran265**
- deleted old scripts
- updated vrdr readme and added tools/readme
- updated credits

### CODE REVIEW

**Review by saulakravitz — APPROVED** [review]
Right now, we are concurrently development VRDR, BFDR and VRCL.
The centralized spreadsheet works well for that.
Is it going to work well in general?

**Comment by ptran265** [comment]
> Right now, we are concurrently development VRDR, BFDR and VRCL. The centralized spreadsheet works well for that. Is it going to work well in general?

I think a centralized spreadsheet prevents the risk of multiple versions of the spreadsheet floating around in each IG. Hopefully with the improved documentation, it will be clear to users how to use/maintain the centralized sheet. Was there something specific that you're concerned/thinking about?

**Comment by saulakravitz** [comment]
Imagine one needs to update the spreadsheet for VRDR STU3.1 and BFDR STU2.1 and the update involves fields defined in VRCL.
Should we recommend that the version of the spreadsheet used to build a version of an IG be checked in with each IG?

From: Patricia Tran ***@***.***>
Date: Tuesday, June 18, 2024 at 11:53 AM
To: HL7/vrdr ***@***.***>
Cc: Saul A Kravitz ***@***.***>, Review requested ***@***.***>
Subject: [EXT] Re: [HL7/vrdr] improved documentation for script usage (PR #70)
Right now, we are concurrently development VRDR, BFDR and VRCL. The centralized spreadsheet works well for that. Is it going to work well in general? I think a centralized spreadsheet prevents the risk of multiple versions of the spreadsheet


Right now, we are concurrently development VRDR, BFDR and VRCL. The centralized spreadsheet works well for that. Is it going to work well in general?

I think a centralized spreadsheet prevents the risk of multiple versions of the spreadsheet floating around in each IG. Hopefully with the improved documentation, it will be clear to users how to use/maintain the centralized sheet. Was there something specific that you're concerned/thinking about?

**Comment by ptran265** [comment]
> that the version of the spreadsheet used to build a version of an IG be checked in with each IG

Ah I see your point. I updated the readme's to include that recommendation.

**Review by rpassas — APPROVED** [review]
I think this looks good - I would maybe just add some notes on when the master sheet should also be updated.

The readme may change a little bit once we reintroduce excel and the script for generating it.

**Pull request merged**
