### PR TITLE
update NIOSH slices

### PR DESCRIPTION
**Pull request by saulakravitz**
This shouldn't change DD, since these slices aren't mapped to any data elements.

### CODE REVIEW

**Review by rpassas — COMMENTED** [review]
Why have VS bindings to [PHVS_Industry_CDC_NAICS2017](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.8067) and [PHVS_Occupation_CDC_SOC2018](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.8068) 

and not [PHVS_Occupation_CDC_Census2018](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.8065) or [PHVS_Industry_CDC_Census2018](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.8066)?

Is it to emphasize that the former codes can be used? (slicing is open)

**Comment by ptran265** [comment]
I can see the VS bindings for occupationCDCCensus2018 and industryCDCCensus2018 slices when I go to the snapshot table tab, but it would be nice if these showed in the differential, especially since that's what's in the DD

**Comment by rpassas** [comment]
> I can see the VS bindings for occupationCDCCensus2018 and industryCDCCensus2018 slices when I go to the snapshot table tab, but it would be nice if these showed in the differential, especially since that's what's in the DD

Ah I missed that - good suggestion

**Comment by saulakravitz** [comment]
If you don't change the bindings, they don't show in the differential.
The slice's ^short is changed, so the slice shows in the differential.   I don't think we can do better than that.

**Review by ptran265 — APPROVED** [review]

**Pull request merged**
